<?php

/**
 * @file
 * Contains flag_click_counter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function flag_click_counter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the flag_click_counter module.
    case 'help.page.flag_click_counter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Counts the number of flags a particular resource has been flagged') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function flag_click_counter_theme() {
  return [
    'flag_click_counter' => [
      'render element' => 'children',
    ],
  ];
}
